# Define language codes
LANGUAGE_CODES = ['en', 'ta', 'hi']

# Language translations
LANGUAGE_PACKS = {
    # English
    'en': {
        'name': 'English',
        'title': 'Credit Card Statement',
        'cardholder_info': 'Cardholder Information',
        'name': 'Name',
        'card_number': 'Card Number',
        'billing_address': 'Billing Address',
        'email': 'Email',
        'phone': 'Phone',
        'statement_summary': 'Statement Summary',
        'amount': 'Amount (INR)',
        'previous_balance': 'Previous Balance',
        'payments_received': 'Payments Received',
        'purchases_charges': 'Purchases & Charges',
        'finance_charges': 'Finance Charges',
        'new_balance': 'New Balance',
        'credit_limit': 'Credit Limit',
        'available_credit': 'Available Credit',
        'transactions': 'Transactions',
        'date': 'Date',
        'description': 'Description',
        'currency_symbol': '₹',
        'payment_due_date': 'Payment Due Date',
        'reward_points': 'Reward Points',
        'generate_statement': 'Generate Statement',
        'download_statement': 'Download Statement',
        'language_selection': 'Select Language',
        'submit': 'Submit',
        'preview': 'Preview',
        # Additional PDF specific translations
        'page': 'Page',
        'of': 'of',
        'statement_date': 'Statement Date',
        'points_earned': 'Points Earned',
        'total_due': 'Total Amount Due',
        'min_due': 'Minimum Amount Due',
        'transaction_date': 'Transaction Date',
        'processing': 'Processing your request...',
        'statement_footer': 'Thank you for your business. For any queries, please contact our customer service.',
        'statement_generated': 'Statement successfully generated!',
        'download_now': 'Download Now',
        'add_transaction': 'Add Transaction',
        'remove': 'Remove',
        # Error messages
        'error_title': 'Error',
        'missing_fields': 'Please fill in all required fields',
        'invalid_card': 'Invalid card number',
        'invalid_email': 'Invalid email address',
        'invalid_phone': 'Invalid phone number',
        'processing_error': 'An error occurred while processing your request'
    },
    
    # Tamil
    'ta': {
        'name': 'தமிழ்',
        'title': 'கிரெடிட் கார்டு அறிக்கை',
        'cardholder_info': 'கார்டு வைத்திருப்பவரின் தகவல்',
        'name': 'பெயர்',
        'card_number': 'கார்டு எண்',
        'billing_address': 'பில்லிங் முகவரி',
        'email': 'மின்னஞ்சல்',
        'phone': 'தொலைபேசி',
        'statement_summary': 'அறிக்கை சுருக்கம்',
        'amount': 'தொகை (INR)',
        'previous_balance': 'முந்தைய இருப்பு',
        'payments_received': 'பெறப்பட்ட கட்டணங்கள்',
        'purchases_charges': 'கொள்முதல் & கட்டணங்கள்',
        'finance_charges': 'நிதிக் கட்டணங்கள்',
        'new_balance': 'புதிய இருப்பு',
        'credit_limit': 'கடன் வரம்பு',
        'available_credit': 'கிடைக்கக்கூடிய கடன்',
        'transactions': 'பரிவர்த்தனைகள்',
        'date': 'தேதி',
        'description': 'விவரம்',
        'currency_symbol': '₹',
        'payment_due_date': 'கட்டணம் செலுத்த வேண்டிய தேதி',
        'reward_points': 'ரிவார்டு புள்ளிகள்',
        'generate_statement': 'அறிக்கையை உருவாக்கவும்',
        'download_statement': 'அறிக்கையைப் பதிவிறக்கவும்',
        'language_selection': 'மொழியை தேர்ந்தெடுக்கவும்',
        'submit': 'சமர்ப்பிக்கவும்',
        'preview': 'முன்னோட்டம்',
        # Additional PDF specific translations
        'page': 'பக்கம்',
        'of': 'இல்',
        'statement_date': 'அறிக்கை தேதி',
        'points_earned': 'பெறப்பட்ட புள்ளிகள்',
        'total_due': 'மொத்த நிலுவைத் தொகை',
        'min_due': 'குறைந்தபட்ச நிலுவைத் தொகை',
        'transaction_date': 'பரிவர்த்தனை தேதி',
        'processing': 'உங்கள் கோரிக்கையை செயலாக்குகிறது...',
        'statement_footer': 'உங்கள் வணிகத்திற்கு நன்றி. ஏதேனும் கேள்விகளுக்கு, எங்கள் வாடிக்கையாளர் சேவையைத் தொடர்பு கொள்ளவும்.',
        'statement_generated': 'அறிக்கை வெற்றிகரமாக உருவாக்கப்பட்டது!',
        'download_now': 'இப்போது பதிவிறக்கவும்',
        'add_transaction': 'பரிவர்த்தனையைச் சேர்க்கவும்',
        'remove': 'அகற்று',
        # Error messages
        'error_title': 'பிழை',
        'missing_fields': 'அனைத்து தேவையான புலங்களையும் நிரப்பவும்',
        'invalid_card': 'தவறான அட்டை எண்',
        'invalid_email': 'தவறான மின்னஞ்சல் முகவரி',
        'invalid_phone': 'தவறான தொலைபேசி எண்',
        'processing_error': 'உங்கள் கோரிக்கையை செயலாக்கும் போது பிழை ஏற்பட்டது'
    },
    
    # Hindi
    'hi': {
        'name': 'हिन्दी',
        'title': 'क्रेडिट कार्ड स्टेटमेंट',
        'cardholder_info': 'कार्डधारक जानकारी',
        'name': 'नाम',
        'card_number': 'कार्ड नंबर',
        'billing_address': 'बिलिंग पता',
        'email': 'ईमेल',
        'phone': 'फोन',
        'statement_summary': 'स्टेटमेंट सारांश',
        'amount': 'राशि (INR)',
        'previous_balance': 'पिछला बैलेंस',
        'payments_received': 'प्राप्त भुगतान',
        'purchases_charges': 'खरीदारी और शुल्क',
        'finance_charges': 'वित्त शुल्क',
        'new_balance': 'नया बैलेंस',
        'credit_limit': 'क्रेडिट लिमिट',
        'available_credit': 'उपलब्ध क्रेडिट',
        'transactions': 'लेनदेन',
        'date': 'तारीख',
        'description': 'विवरण',
        'currency_symbol': '₹',
        'payment_due_date': 'भुगतान करने की तारीख',
        'reward_points': 'रिवॉर्ड पॉइंट्स',
        'generate_statement': 'स्टेटमेंट बनाएं',
        'download_statement': 'स्टेटमेंट डाउनलोड करें',
        'language_selection': 'भाषा चुनें',
        'submit': 'सबमिट करें',
        'preview': 'पूर्वावलोकन',
        # Additional PDF specific translations
        'page': 'पृष्ठ',
        'of': 'का',
        'statement_date': 'स्टेटमेंट तारीख',
        'points_earned': 'अर्जित अंक',
        'total_due': 'कुल देय राशि',
        'min_due': 'न्यूनतम देय राशि',
        'transaction_date': 'लेनदेन तारीख',
        'processing': 'आपके अनुरोध पर प्रक्रिया हो रही है...',
        'statement_footer': 'आपके व्यापार के लिए धन्यवाद। किसी भी प्रश्न के लिए, कृपया हमारी ग्राहक सेवा से संपर्क करें।',
        'statement_generated': 'स्टेटमेंट सफलतापूर्वक उत्पन्न किया गया!',
        'download_now': 'अभी डाउनलोड करें',
        'add_transaction': 'लेनदेन जोड़ें',
        'remove': 'हटाएं',
        # Error messages
        'error_title': 'त्रुटि',
        'missing_fields': 'कृपया सभी आवश्यक फ़ील्ड भरें',
        'invalid_card': 'अमान्य कार्ड नंबर',
        'invalid_email': 'अमान्य ईमेल पता',
        'invalid_phone': 'अमान्य फोन नंबर',
        'processing_error': 'आपके अनुरोध को संसाधित करते समय एक त्रुटि हुई'
    }
}
